# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-introduction
build:
  artifacts:
    - image: skaffold-introduction
      jib: { }
  tagPolicy:
    sha256: { }
deploy:
  kubectl:
    manifests:
      - k8s/mydeployment.yaml
      - k8s/myservice.yaml
profiles:
  - name: test
    test:
      - image: skaffold-introduction
        custom:
          - command: mvn test -Dmaven.test.skip=false
  - name: sync
    build:
      artifacts:
        - image: skaffold-introduction
          sync:
            auto: true
          jib: { }
  - name: docker
    build:
      artifacts:
        - image: skaffold-introduction
          docker:
            dockerfile: Dockerfile
